### ISSUE TITLE
Is this added to dontgo403?

### ISSUE THREAD

**Issue by ghost** [devploit/dontgo403#12]
I recently read article on 403 bypass here:
https://medium.com/@abbasheybati1/403-bypass-lyncdiscover-microsoft-com-db2778458c33

Iwant to know is dontgo403 does this or not? If not how i can add this?

**Comment by devploit** [comment]
Hi!

Actually dontgo403 doesn't change the protocol to HTTP1.0 to try to bypass 403 error messages but sounds interesting. I will add it in future releases.

Thanks for the information. I will close the issue when it is implemented.

**Comment by coolerspeex** [comment]
Cool, if it's implemented little quick will be awesome,
can't wait to find some more bypasses :) your tool really help me
Thanks

**Comment by coolerspeex** [comment]
is this implemented yet?

**Comment by devploit** [comment]
Implemented in the latest release: https://github.com/devploit/dontgo403/releases/tag/0.9.4
