### ISSUE TITLE
invalid URL escape "%"

### ISSUE THREAD

**Issue by cyb3rsalih** [devploit/dontgo403#17]
I am getting this when program starting 
`CUSTOM PATHS`

```
[####] CUSTOM PATHS [####]
2022/09/11 13:37:26 parse "https://REDACTED.DOMAIN/admin.php%": invalid URL escape "%"
```

**Comment by devploit** [comment]
That's right, that payloads is not working properly. Now is deleted from the list. You can update to the last version to check if all is working right.
