### ISSUE TITLE
` open payloads/httpmethods: no such file or directory` issue

### ISSUE THREAD

**Issue by s41n1k** [devploit/dontgo403#19]
Hi,
When I run the below error occurred.
```
./dontgo403 -u https://www.target.com/shoppingcart

[####] HTTP METHODS [####]
2022/09/14 23:03:47 open payloads/httpmethods: no such file or directory
```

**Comment by devploit** [comment]
You need to run the binary from the same folder as payloads is or use the flag -f to specify where is the payloads folder.

**Comment by Aelsaedy** [comment]
Same Error 
2024/09/02 12:09:53 Error reading /httpmethods file: open payloads/httpmethods: no such file or directory
any  solution
