### ISSUE TITLE
Tool Crash

### ISSUE THREAD

**Issue by ghost** [devploit/dontgo403#23]
_[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x468041]
goroutine 1 [running]:
fmt.(*buffer).writeString(...)
	/usr/lib/go-1.19/src/fmt/print.go:82
fmt.(*fmt).padString(0x41b7c6?, {0x0, 0x13})
	/usr/lib/go-1.19/src/fmt/format.go:110 +0x247
fmt.(*fmt).fmtS(0xc0002d00d0?, {0x0?, 0xc00010c800?})
	/usr/lib/go-1.19/src/fmt/format.go:359 +0x3f
fmt.(*pp).fmtString(0x4f4bc6?, {0x0?, 0xc0004429e9?}, 0x0?)
	/usr/lib/go-1.19/src/fmt/print.go:474 +0x86
fmt.(*pp).printArg(0xc0002d00d0, {0x7e7bc0?, 0xc0004729a0}, 0x76)
	/usr/lib/go-1.19/src/fmt/print.go:725 +0x21e
fmt.(*pp).doPrintf(0xc0002d00d0, {0xc000442a07, 0x9}, {0xc00010cac8?, 0x3, 0x3})
	/usr/lib/go-1.19/src/fmt/print.go:1057 +0x288
fmt.Fprintf({0x919d00, 0xc000706580}, {0xc000442a07, 0x9}, {0xc00010cac8, 0x3, 0x3})
	/usr/lib/go-1.19/src/fmt/print.go:204 +0x75
github.com/cheynewallace/tabby.(*Tabby).AddLine(0xc000014008, {0xc00010cac8, 0x3, 0x3})
	/root/go/pkg/mod/github.com/cheynewallace/tabby@v1.1.1/tabby.go:31 +0x59
dontgo403/cmd.printResponse({0xc00092e000, 0x550, 0xc0000264ac?})
	/home/dontgo403/cmd/requester.go:36 +0x2f6
dontgo403/cmd.requestHeaders({0xc0003ee4e0, 0x2f}, {0xc0005926e0, 0x1, 0x1}, 0xc000169b90, {0x0, 0x0}, {0x7ffcc82d3310, 0xe}, ...)
	/home/dontgo403/cmd/requester.go:136 +0x2d3
dontgo403/cmd.requester({0xc000129919, 0x2e}, {0x0?, 0x0?}, {0x7ffcc82d3322, 0x6f}, {0xc000037100, 0x1, 0x0?}, {0x0, ...}, ...)
	/home/dontgo403/cmd/requester.go:291 +0x385
dontgo403/cmd.glob..func1(0xb7bd80?, {0x861224?, 0x6?, 0x6?})
	/home/dontgo403/cmd/root.go:48 +0x31c
github.com/spf13/cobra.(*Command).execute(0xb7bd80, {0xc000024080, 0x6, 0x6})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xb7bd80)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
dontgo403/cmd.Execute()
	/home/dontgo403/cmd/root.go:63 +0x25
main.main()
	/home/dontgo403/main.go:22 +0x17_

**Comment by devploit** [comment]
Hi, can you download the latest refactored version and try again?
