### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [devploit/dontgo403#3]
It would be very helpful if you could tag releases as well. This would enable distributions to fetch the source from GitHub instead of working with git checkouts.

Thanks

**Comment by devploit** [comment]
Hi @fabaff,

Do you mean uploading releases of the already compiled binary? If the tool is improved by increasing its functionalities, future version commits will be clearer. Sorry for a bunch of commits these first days.

**Comment by fabaff** [comment]
End-users need binaries. Distributions need the source code to build.

E.g., add tags would be sufficient:

```bash
$ git tag -a 0.1.2 && git push origin 0.1.2
```

will create a downloadable tarball for 0.1.2.

**Comment by devploit** [comment]
Thanks for the tip. Tag added in the latest commit.

**Comment by fabaff** [comment]
Thank you.

**Comment by fabaff** [comment]
As reference: https://github.com/NixOS/nixpkgs/pull/157255
